import Link from 'next/link';

const subjects = [
  { key:'toan', name:'Toán học', icon:'∑', color:'lavender', desc:'Tư duy và vận dụng' },
  { key:'ngu-van', name:'Ngữ văn', icon:'Aa', color:'peach', desc:'Đọc hiểu và làm văn' },
  { key:'vat-ly', name:'Vật lý', icon:'ϟ', color:'blue', desc:'Nắm chắc công thức' },
  { key:'hoa-hoc', name:'Hóa học', icon:'⚗', color:'mint', desc:'Lý thuyết và bài tập' },
  { key:'lich-su', name:'Lịch sử', icon:'◷', color:'yellow', desc:'Hệ thống kiến thức' },
  { key:'dia-ly', name:'Địa lý', icon:'⌖', color:'rose', desc:'Atlat và số liệu' }
];

export default function HomePage() {
  return <>
    <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> NỀN TẢNG LUYỆN THI THPT</div><h1>Chinh phục mục tiêu.<br/><em>Bứt phá điểm số.</em></h1><p className="hero-lede">Ôn tập theo môn, luyện đề có đồng hồ và theo dõi kết quả của bạn qua từng lần làm bài.</p><div className="hero-actions"><Link href="/de-thi" className="button button-primary button-large">Khám phá kho đề <span>→</span></Link><Link href="/dang-ky" className="button button-outline button-large">Bắt đầu miễn phí</Link></div><div className="hero-proof"><div className="avatar-stack"><span>T</span><span>M</span><span>H</span></div><span><strong>Học có kế hoạch</strong><br/><small>Theo dõi tiến độ từng ngày</small></span></div></div><div className="hero-art" aria-label="Minh họa học tập"><div className="art-sun"/><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-paper"><div className="paper-top"><span>MOCK EXAM</span><span className="paper-badge">01 / 04</span></div><div className="paper-title">Bài luyện tập<br/><b>Toán học</b></div><div className="paper-line long"/><div className="paper-line"/><div className="paper-question"><span>01</span><div><div className="paper-line long"/><div className="paper-line short"/></div></div><div className="paper-options"><span>A</span><span className="picked">B</span><span>C</span><span>D</span></div><div className="paper-progress"><span/></div></div><div className="floating-score"><div className="score-icon">↗</div><div><strong>Tiến bộ mỗi ngày</strong><small>Kiên trì tạo khác biệt</small></div></div><div className="floating-note"><span>✓</span> Học theo nhịp của bạn</div></div></div></section>
    <section className="section subjects-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">BẮT ĐẦU TỪ HÔM NAY</div><h2>Chọn môn, vào guồng học tập</h2><p>Chia nhỏ mục tiêu để việc ôn thi trở nên dễ kiểm soát hơn.</p></div><Link href="/de-thi" className="text-link">Xem tất cả đề thi <span>→</span></Link></div><div className="subject-grid">{subjects.map(s=><Link key={s.key} href={`/de-thi?mon=${s.key}`} className="subject-card"><div className={`subject-icon ${s.color}`}>{s.icon}</div><div className="subject-copy"><h3>{s.name}</h3><p>{s.desc}</p></div><span className="subject-arrow">↗</span></Link>)}</div></div></section>
    <section className="section how-section"><div className="container how-grid"><div><div className="eyebrow">HỌC CÓ CHIẾN LƯỢC</div><h2>Mỗi lần luyện đề,<br/><em>hiểu mình hơn một chút.</em></h2><p className="muted">Làm bài, xem kết quả và quay lại đúng phần kiến thức cần cải thiện.</p><Link href="/de-thi" className="button button-dark button-large">Vào kho đề thi <span>→</span></Link></div><div className="steps-list"><div className="step-row"><span className="step-no">01</span><div><h3>Chọn đề phù hợp</h3><p>Lọc theo môn và thời lượng để bắt đầu vừa sức.</p></div><span className="step-symbol">⌕</span></div><div className="step-row"><span className="step-no">02</span><div><h3>Làm bài tập trung</h3><p>Đồng hồ và phiếu trả lời giúp bạn quen áp lực thời gian.</p></div><span className="step-symbol">◷</span></div><div className="step-row"><span className="step-no">03</span><div><h3>Xem điểm và lời giải</h3><p>Biết câu nào đúng, câu nào cần ôn lại.</p></div><span className="step-symbol">✓</span></div></div></div></section>
    <section className="bottom-cta"><div className="container cta-inner"><div><div className="eyebrow light-eyebrow">LỘ TRÌNH BẮT ĐẦU TỪ BẠN</div><h2>Sẵn sàng cho lần luyện đề tiếp theo?</h2><p>Tạo tài khoản để lưu lịch sử và theo dõi tiến bộ của riêng mình.</p></div><Link href="/dang-ky" className="button button-light button-large">Tạo tài khoản <span>→</span></Link></div></section>
  </>;
}
