'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
const initialQuestion = JSON.stringify([{prompt:'Ví dụ: 2 + 3 bằng bao nhiêu?',type:'single_choice',points:1,options:[{id:'A',text:'4'},{id:'B',text:'5'},{id:'C',text:'6'},{id:'D',text:'7'}],answerKey:['B'],acceptedAnswers:[],explanation:'2 + 3 = 5.'}],null,2);
export default function AdminClient(){
 const [exams,setExams]=useState([]);const [user,setUser]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:'',slug:'',subject:'toan',description:'',durationMinutes:45,published:false,questions:initialQuestion});
 async function load(){setLoading(true);setError('');try{const me=await fetch('/api/auth/me',{cache:'no-store'});const md=await me.json();if(!me.ok)throw new Error('Cần đăng nhập bằng tài khoản quản trị đã được thiết lập qua biến ADMIN_EMAIL.');if(md.user?.role!=='admin')throw new Error('Tài khoản hiện tại không có quyền admin.');setUser(md.user);const r=await fetch('/api/admin/exams',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không tải được danh sách.');setExams(d.exams||[]);}catch(e){setError(e.message);}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function change(k,v){setForm(f=>({...f,[k]:v,...(k==='title'&&!f.slug?{slug:v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}: {})}))}
 async function create(event){event.preventDefault();setBusy(true);setError('');setNotice('');try{let questions;try{questions=JSON.parse(form.questions)}catch{throw new Error('Phần câu hỏi JSON chưa đúng cú pháp. Ví dụ mẫu đã được điền sẵn.')}const r=await fetch('/api/admin/exams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,durationMinutes:Number(form.durationMinutes),questions})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không tạo được đề.');setNotice('Đã tạo đề '+d.exam.title+'.');setForm(f=>({...f,title:'',slug:'',description:''}));await load();}catch(e){setError(e.message);}finally{setBusy(false)}}
 async function publish(exam){setError('');const r=await fetch(`/api/admin/exams/${exam.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({isPublished:!exam.is_published})});const d=await r.json();if(!r.ok){setError(d.error||'Không cập nhật được đề.');return}setExams(es=>es.map(x=>x.id===exam.id?{...x,is_published:d.exam.is_published}:x));}
 if(loading)return <div className="loading-card">Đang kiểm tra quyền quản trị…</div>;
 if(!user)return <div className="alert alert-warning">{error}<p>Để tạo admin lần đầu, cấu hình ADMIN_EMAIL và ADMIN_PASSWORD trong môi trường máy chủ rồi chạy `npm run db:init` theo README. Không có mật khẩu mặc định.</p><Link href="/dang-nhap" className="button button-primary">Đăng nhập</Link></div>;
 return <><div className="admin-banner"><div><strong>Đăng nhập quản trị: {user.email}</strong><p>Đề do quản trị viên thêm sẽ được lưu vào PostgreSQL. Không có dữ liệu thật tự động nhập từ DOL THPT.</p></div><button className="button button-quiet" onClick={load}>Làm mới</button></div>{error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="alert alert-success">{notice}</div>}
 <div className="admin-layout"><section className="admin-list"><div className="panel-heading"><h2>Kho đề hiện có</h2><span>{exams.length} đề</span></div>{exams.map(ex=><article className="admin-exam-row" key={ex.id}><div><strong>{ex.title}</strong><p>{ex.subject} · {ex.question_count} câu {ex.is_sample?'· Minh họa':''}</p></div><div className="admin-exam-actions"><span className={ex.is_published?'published-pill':'draft-pill'}>{ex.is_published?'Đang hiển thị':'Bản nháp'}</span><button className="button button-small button-outline" onClick={()=>publish(ex)}>{ex.is_published?'Ẩn đề':'Xuất bản'}</button></div></article>)}{!exams.length&&<p className="muted">Chưa có đề nào. Hãy tạo đề bên cạnh.</p>}</section>
 <section className="admin-form-panel"><div className="panel-heading"><h2>Tạo đề mới</h2></div><form className="form-stack" onSubmit={create}><label>Tên đề<input required value={form.title} onChange={e=>change('title',e.target.value)} maxLength={200} placeholder="Ví dụ: Toán học - Đề minh họa 01"/></label><label>Slug URL<input required value={form.slug} onChange={e=>change('slug',e.target.value)} maxLength={100} placeholder="toan-de-minh-hoa-01"/><small>Dùng chữ thường, số và dấu gạch ngang.</small></label><label>Môn học<select value={form.subject} onChange={e=>change('subject',e.target.value)}><option value="toan">Toán học</option><option value="ngu-van">Ngữ văn</option><option value="vat-ly">Vật lý</option><option value="hoa-hoc">Hóa học</option><option value="sinh-hoc">Sinh học</option><option value="lich-su">Lịch sử</option><option value="dia-ly">Địa lý</option><option value="tieng-anh">Tiếng Anh</option></select></label><label>Mô tả<textarea rows="2" value={form.description} onChange={e=>change('description',e.target.value)} maxLength={1000}/></label><label>Thời lượng (phút)<input type="number" min="1" max="360" required value={form.durationMinutes} onChange={e=>change('durationMinutes',e.target.value)}/></label><label>Câu hỏi (JSON)<textarea className="json-input" rows="17" spellCheck="false" value={form.questions} onChange={e=>change('questions',e.target.value)}/><small>Giữ định dạng mẫu. Với câu trắc nghiệm, answerKey là mảng ID đáp án đúng, ví dụ ["B"]. Có thể tạo nhiều câu trong mảng.</small></label><label className="inline-check"><input type="checkbox" checked={form.published} onChange={e=>change('published',e.target.checked)}/> Xuất bản ngay sau khi tạo</label><button className="button button-primary button-large" disabled={busy}>{busy?'Đang lưu…':'Tạo đề thi →'}</button></form></section></div></>;
}
