'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
export default function DashboardClient(){
 const [user,setUser]=useState(null); const [attempts,setAttempts]=useState([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch('/api/auth/me',{cache:'no-store'});if(r.status===401){if(live)setError('Bạn chưa đăng nhập. Hãy đăng nhập để xem lịch sử bài làm.');return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Không lấy được tài khoản.');if(live)setUser(d.user);const ar=await fetch('/api/user/attempts',{cache:'no-store'});const ad=await ar.json();if(!ar.ok)throw new Error(ad.error||'Không tải được lịch sử.');if(live)setAttempts(ad.attempts||[]);}catch(e){if(live)setError(e.message);}finally{if(live)setLoading(false);}})();return()=>{live=false}},[]);
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/dang-nhap');}
 return <>{loading&&<div className="loading-card">Đang tải tài khoản…</div>}{error&&<div className="alert alert-warning">{error}<p><Link href="/dang-nhap" className="text-link">Đăng nhập →</Link></p></div>}{user&&<><div className="dashboard-welcome"><div className="welcome-avatar">{(user.display_name||'H').slice(0,1).toUpperCase()}</div><div><h2>Chào {user.display_name}</h2><p>{user.email} · {user.role==='admin'?'Quản trị viên':'Học viên'}</p></div><button className="button button-quiet" onClick={logout}>Đăng xuất</button></div><div className="stats-grid"><div className="stat-card"><small>Số bài đã nộp</small><strong>{attempts.length}</strong><span>Lịch sử được lưu trên database</span></div><div className="stat-card"><small>Điểm trung bình</small><strong>{attempts.length?(attempts.reduce((s,a)=>s+(Number(a.max_score)?Number(a.score)/Number(a.max_score)*100:0),0)/attempts.length).toFixed(1)+'%':'—'}</strong><span>Tính từ bài đã nộp</span></div><div className="stat-card"><small>Vai trò</small><strong>{user.role==='admin'?'Admin':'Học viên'}</strong><span>Phân quyền được kiểm tra ở máy chủ</span></div></div><div className="history-head"><h2>Lịch sử làm bài</h2><Link href="/de-thi" className="text-link">Luyện đề mới →</Link></div>{attempts.length===0?<div className="empty-state compact"><h3>Bạn chưa nộp bài nào</h3><p>Bắt đầu từ một đề minh họa trong kho đề thi.</p><Link href="/de-thi" className="button button-primary">Chọn đề thi</Link></div>:<div className="table-wrap"><table><thead><tr><th>Đề thi</th><th>Môn</th><th>Điểm</th><th>Ngày nộp</th></tr></thead><tbody>{attempts.map(a=><tr key={a.id}><td><Link href={`/lam-bai/${a.slug}`}>{a.title}</Link></td><td>{a.subject}</td><td><strong>{Number(a.score).toFixed(1)} / {Number(a.max_score).toFixed(1)}</strong></td><td>{new Date(a.submitted_at).toLocaleString('vi-VN')}</td></tr>)}</tbody></table></div>}{user.role==='admin'&&<p className="admin-shortcut"><Link className="button button-dark" href="/admin">Mở khu vực quản trị →</Link></p>}</>}</>;
}
