'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
function displayTime(value){const m=Math.floor(value/60).toString().padStart(2,'0');const s=(value%60).toString().padStart(2,'0');return `${m}:${s}`;}
export default function ExamRunner({slug}){
 const [data,setData]=useState(null); const [answers,setAnswers]=useState({}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [seconds,setSeconds]=useState(null); const [sending,setSending]=useState(false); const [result,setResult]=useState(null);
 useEffect(()=>{let live=true;fetch(`/api/exams/${encodeURIComponent(slug)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Không tải được đề.');return d;}).then(d=>{if(live){setData(d);setSeconds(Number(d.exam.duration_minutes)*60);}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[slug]);
 useEffect(()=>{if(seconds===null||seconds<=0||result||loading)return;const t=setTimeout(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearTimeout(t)},[seconds,result,loading]);
 useEffect(()=>{if(seconds===0&&!sending&&!result&&data){submitAnswers(true)}},[seconds]);
 const answered=useMemo(()=>Object.keys(answers).filter(k=>{const a=answers[k];return Array.isArray(a)?a.length>0:String(a??'').trim().length>0}).length,[answers]);
 function changeAnswer(q,value,multi=false){setAnswers(old=>{const previous=Array.isArray(old[q.id])?old[q.id]:[];return {...old,[q.id]:multi?(previous.includes(value)?previous.filter(v=>v!==value):[...previous,value]):value};});}
 async function submitAnswers(auto=false){if(sending||result||!data)return;if(!auto&&!window.confirm('Nộp bài và chấm điểm? Sau khi nộp sẽ hiện đáp án và lời giải.'))return;setSending(true);setError('');try{const response=await fetch(`/api/exams/${encodeURIComponent(slug)}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});const d=await response.json();if(!response.ok)throw new Error(d.error||'Nộp bài không thành công.');setResult(d);setSeconds(0);}catch(e){setError(e.message);}finally{setSending(false)}}
 if(loading)return <div className="loading-card">Đang tải đề thi…</div>;if(error&&!data)return <div className="empty-state"><h2>Không mở được đề thi</h2><p>{error}</p><Link href="/de-thi" className="button button-primary">Về kho đề thi</Link></div>;if(!data)return null;
 return <><div className="exam-run-header"><div><div className="eyebrow">{data.exam.subject} {data.exam.is_sample?'· ĐỀ MINH HỌA':''}</div><h1>{data.exam.title}</h1><p className="muted">{data.exam.description}</p></div><div className={`timer-box ${seconds<=300?'timer-warning':''}`}><small>THỜI GIAN CÒN LẠI</small><strong>{displayTime(seconds||0)}</strong></div></div>
 {result?<section className="result-panel"><div className="result-check">✓</div><div className="eyebrow">ĐÃ LƯU KẾT QUẢ</div><h2>{Number(result.attempt.score).toFixed(1)} <span>/ {Number(result.attempt.max_score).toFixed(1)}</span></h2><p className="result-percent">{result.percentage}% điểm tối đa</p><p className="muted">Kết quả đã được lưu vào lịch sử tài khoản.</p><div className="result-actions"><Link href="/dashboard" className="button button-primary">Xem lịch sử</Link><Link href="/de-thi" className="button button-outline">Chọn đề khác</Link></div><div className="review-list"><h3>Đáp án và lời giải</h3>{result.questions.map((q,i)=><article className="review-question" key={q.id}><div className="review-heading"><strong>Câu {i+1}</strong><span className={q.correct?'status-correct':'status-wrong'}>{q.correct?'Đúng':'Chưa đúng'} · {q.earned}/{q.points} điểm</span></div><p>{q.prompt}</p>{q.type==='short_answer'?<p className="answer-line">Đáp án: {(q.answerKey||[]).join(', ')||'Chưa thiết lập'}</p>:<div className="answer-line">Đáp án đúng: {(q.answerKey||[]).join(', ')}</div>}{q.explanation&&<p className="explanation">{q.explanation}</p>}</article>)}</div></section>:<><div className="exam-progress"><div><span>{answered}/{data.questions.length} câu đã trả lời</span><span>{data.exam.duration_minutes} phút</span></div><div className="progress-track"><span style={{width:`${data.questions.length?answered/data.questions.length*100:0}%`}}/></div></div><div className="question-list">{data.questions.map((q,i)=><article className="question-card" key={q.id}><div className="question-number">CÂU {String(i+1).padStart(2,'0')} <span>{q.points} điểm</span></div><h3>{q.prompt}</h3>{q.type==='short_answer'?<input className="short-answer" value={answers[q.id]||''} onChange={e=>changeAnswer(q,e.target.value)} placeholder="Nhập đáp án của bạn"/>:<div className="choice-list">{q.options.map(o=>{const isMulti=q.type==='multi_choice';const checked=isMulti?(answers[q.id]||[]).includes(o.id):answers[q.id]===o.id;return <label className={checked?'choice-row selected':'choice-row'} key={o.id}><input type={isMulti?'checkbox':'radio'} name={q.id} checked={Boolean(checked)} onChange={()=>changeAnswer(q,o.id,isMulti)}/><span className="choice-letter">{o.label}</span><span>{o.text}</span></label>})}</div>}</article>)}</div><div className="submit-bar">{error&&<div className="alert alert-error">{error}</div>}<span className="muted">Kiểm tra lại đáp án trước khi nộp. Cần đăng nhập để lưu kết quả.</span><button className="button button-primary button-large" disabled={sending} onClick={()=>submitAnswers(false)}>{sending?'Đang chấm…':'Nộp bài và xem điểm →'}</button></div></>}
 </>;
}
